name: Unit Testing

# Controls when the workflow will run
on [push]:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  python-test:
    name: 'test'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: tests/environment.yml
          environment-name: myenv
      - name: Unit testing
        shell: bash -l {0}
        run: |
              python -m unittest discover -s tests -p "*.py"
